---
title: "Probability"
sidebar: false
---

Welcome to the website for Middlebury College's Fall 2023 MATH/STAT 310. On this website you will find the course syllabus, schedule, and assignments. The website is frequently updated during the semester, so please make a habit of refreshing the page. The icons at the top right will link to the online version of the textbook and Canvas.

## Major Announcements

-   Ice-cream social and spring course advising: **Tuesday, November 7** starting at **3:45pm in Davis Family Library 105A/B**.

-   We will have one more job talk for the Assistant Professor of Statistics position in a few weeks. You are highly encouraged to attend, especially if you are considering declaring a Statistics major!

    -   Maddie Rainey: Thursday, 11/02 at 12:30-1:20pm in Warner 101

        -   Talk title: "Modeling Spatial Data with the Flexibility of Spatial Splines"

-   Details about [**Midterm 2**](/exam.qmd#sec-midterm2)! Please email me ASAP if you have a conflict with the in-person component.

## Course Details

Instructor: Becky Tang

-   Office: WNS 214
-   Email: btang\@middlebury.edu

Meeting times: TRF 8:40-9:30am in WNS 105

Office hours: M 2-4pm, R 3-4pm

[Syllabus](Stat310_Syllabus.pdf) (most recent update: 9/12/23 to say assignments should be submitted to Canvas)

## 
