---
title: "Schedule"
format: 
  html: 
    toc: false
---

A high-level overview of the semester's topics are presented here. Please select a week for a specific day's assignments and materials.

### [Week 01](weeks/week-01.qmd)

-   Welcome

-   Probability axioms

### [Week 02](weeks/week-02.qmd)

-   R and RStudio

-   Conditional probability

-   Independence of events

### [Week 03](weeks/week-03.qmd)

-   Monty Hall

-   Bernoulli and Binomial

### [Week 04](weeks/week-04.qmd)

-   CDF

-   Independence of RVs

-   Expected value

### [Week 05](weeks/week-05.qmd)

-   Geometric and Negative Binomial Distributions

-   Midterm 1

### [Week 06](weeks/week-06.qmd)

-   Variance

-   Poisson distribution

-   Continuous random variables

### [Week 07](weeks/week-07.qmd)

-   Uniform distribution

-   Normal distribution

-   Exponential distribution

### [Week 08](weeks/week-08.qmd)

-   Moments

-   Recap Taylor Series

-   MGF

### [Week 09](weeks/week-09.qmd)

-   Joint distributions
-   Covariance and correlation

### [Week 10](weeks/week-10.qmd)

-   Change of variable (2-D)
-   [**Midterm II**](/exam.qmd#sec-midterm2) (in-person and take-home)

### Thanksgiving Break!

### [Week 11](weeks/week-11.qmd)

-   Beta distribution
-   Gamma distribution
-   Order statistics
-   Conditional expectation

### [Week 12](weeks/week-12.qmd)

-   Conditional variance
-   Law of Large Numbers
-   Central Limit Theorem

### [Week 13](weeks/week-13.qmd)

-   CLT in `R`
-   Final exam
